// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACShLJ5ByejG6xkhpEWYa0Dpu2dHA_M_g',
    appId: '1:810995389532:web:4246b292f245b0e6f80299',
    messagingSenderId: '810995389532',
    projectId: 'tenbyte-92bda',
    authDomain: 'tenbyte-92bda.firebaseapp.com',
    storageBucket: 'tenbyte-92bda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp8S3Zqmb93UUOiz-yoEKSLACdtUjNvpw',
    appId: '1:810995389532:android:91e9b6ee03bea14df80299',
    messagingSenderId: '810995389532',
    projectId: 'tenbyte-92bda',
    storageBucket: 'tenbyte-92bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy9aLOVjo17abvppDjWtzJ8lBtXmC43cg',
    appId: '1:810995389532:ios:0f817ae29475ae43f80299',
    messagingSenderId: '810995389532',
    projectId: 'tenbyte-92bda',
    storageBucket: 'tenbyte-92bda.appspot.com',
    iosBundleId: 'com.example.tenbytes',
  );
}
